--Khởi tạo Database
CREATE DATABASE QuanLyCangTin

--Sử dụng Database
USE QuanLyCangTin

--Khởi tạo Table 
CREATE TABLE NguoiDung
(
	MaND CHAR(10) PRIMARY KEY,
	TenND NVARCHAR(50) NOT NULL,
	GioiTinh NVARCHAR(10) NOT NULL,
	NgaySinh DATE NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	SDT NVARCHAR(10) NOT NULL,
)

CREATE TABLE TaiKhoan
(
	TenDangNhap NVARCHAR(50) PRIMARY KEY,
	MatKhau NVARCHAR(50) NOT NULL,
	Quyen NVARCHAR(50) NOT NULL,
	MaND CHAR(10) NOT NULL,
	--MaTK INT FOREIGN KEY REFERENCES TaiKhoan(MaTK)
	CONSTRAINT FK_TaiKhoan_ND FOREIGN KEY (MaND) REFERENCES NguoiDung(MaND)
);

CREATE TABLE DanhMuc
(
	MaDM CHAR(10) PRIMARY KEY,
	TenDanhMuc NVARCHAR(50) NOT NULL,
)

CREATE TABLE ThucDon
(
	MaMon CHAR(10) PRIMARY KEY,
	TenMon NVARCHAR(50) NOT NULL,
	MaDM CHAR(10) NOT NULL,
	SoLuong FLOAT NOT NULL,
	DonGia FLOAT NOT NULL,
	Anh NVARCHAR(200) NOT NULL,
	GhiChu NVARCHAR(200) NOT NULL,
	CONSTRAINT FK_ThucDon_DM FOREIGN KEY (MaDM) REFERENCES DanhMuc(MaDM)
)

CREATE TABLE KhachHang
(
	MaKH CHAR(10) PRIMARY KEY,
	TenKH NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	SDT NVARCHAR(10) NOT NULL
);

CREATE TABLE HoaDon 
(
	MaHD CHAR(50) PRIMARY KEY,
    MaND CHAR(10) NOT NULL,
	MaKH CHAR(10) NOT NULL,
	NgayBan DATETIME NOT NULL,
    TongTien FLOAT(53) NOT NULL,
    CONSTRAINT FK_HoaDon_ND FOREIGN KEY (MaND) REFERENCES NguoiDung(MaND),
    CONSTRAINT FK_HoaDon_KH FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

CREATE TABLE ChiTietHD 
(
	MaHD CHAR(50) ,
    MaMon CHAR(10) ,
	SoLuong FLOAT NOT NULL,
	DonGia FLOAT NOT NULL,
	GiamGia FLOAT NOT NULL,
	ThanhTien FLOAT NOT NULL,
    PRIMARY KEY CLUSTERED (MaHD ASC, MaMon ASC)
);

INSERT INTO NguoiDung(MaND, TenND, GioiTinh, NgaySinh, DiaChi, SDT)
VALUES ('ND01', 'admin', 'Nam', '2002-09-28', 'Ha Noi', '0999999999')

INSERT INTO TaiKhoan(TenDangNhap, MatKhau, Quyen, MaND)
VALUES ('admin', 'Admin123@', 'Admin', 'ND01')

CREATE PROCEDURE BCMHDTheoNgay
    @Ngay DATE
AS
BEGIN
	SELECT HD.MaHD, HD.NgayBan, HD.TongTien, TD.TenMon, CT.DonGia, CT.SoLuong, CT.ThanhTien
	FROM HoaDon HD
	INNER JOIN ChiTietHD CT ON HD.MaHD = CT.MaHD
	INNER JOIN ThucDon TD ON CT.MaMon = CT.MaMon
    WHERE CONVERT(DATE, HD.NgayBan) = @Ngay;
END;